
### ACM
- name: "Enable ACM API in GCP"
  command:
    cmd: gcloud beta container hub config-management enable
  run_once: true # only needs to run once
  when: "(primary_cluster_machine is defined) and (primary_cluster_machine == true)"
  environment:
    PATH: "{{ tools_base_path }}/google-cloud-sdk/bin:{{ ansible_env.PATH }}"
  tags:
  - abm-software
  - enable-acm

### ACM Setup

# Check for ACM Operator
- name: "Test for config-management-system namespace"
  include_tasks: kubectl-presence.yml
  vars:
    name: "config-management-system"
    type: "namespaces"
    namespace: ""
    kubeconfig: "{{ kubeconfig_shared_location }}"
    fact_name: "has_acm_ns"
  when: "(primary_cluster_machine is defined) and (primary_cluster_machine == true)"
  tags:
  - acm-operator

# # Download operator
- name: "Create config-management-system namespace if needed"
  command:
    cmd: "kubectl create ns config-management-system"
  environment:
    KUBECONFIG: "{{ kubeconfig_shared_location }}"
  when:
    - (primary_cluster_machine is defined)
    - (primary_cluster_machine == true)
    - (has_acm_ns == false)
  tags:
  - acm-root-repo

# Check for ACM Operator
- name: "Test for config-management operator presence"
  include_tasks: kubectl-presence.yml
  vars:
    name: "config-management"
    type: "configmanagements.configmanagement.gke.io"
    namespace: ""
    kubeconfig: "{{ kubeconfig_shared_location }}"
    fact_name: "has_acm_operator"
  when: "(primary_cluster_machine is defined) and (primary_cluster_machine == true)"
  tags:
  - acm-operator

- name: "Copy over apply-spec file"
  template:
    src: apply-spec.yaml.j2
    dest: "{{ acm_config_files }}/apply-spec.yaml"
  when:
    - (primary_cluster_machine is defined)
    - (primary_cluster_machine == true)
  tags:
  - acm-config-management
  - updated-acm

- name: "Install ACM Operator"
  shell: |
      gcloud beta container fleet config-management apply --membership={{ cluster_name }} --config={{ acm_config_files }}/apply-spec.yaml --project={{ google_project_id }}
  args:
    executable: /bin/bash
  when:
    - (primary_cluster_machine is defined)
    - (primary_cluster_machine == true)
    - (has_acm_operator == false)
  retries: 5
  delay: 10
  register: result
  until: result.rc == 0
  tags:
  - acm-operator

#### Root Repo Configuration

# NOTE: If the git-creds secret already exists, no action is taken. There is NO effort to determine what type of secret so switching between types requires removal of the `git-creds` secret within the cluster
- name: "Test for existing RootRepo git-creds secret"
  include_tasks: kubectl-presence.yml
  vars:
    name: "{{ root_repository_git_secret_name }}"
    type: "secrets"
    namespace: "config-management-system"
    kubeconfig: "{{ kubeconfig_shared_location }}"
    fact_name: "has_root_repo_secret"
  tags:
  - acm-root-repo

- name: "Create dependencies for RootRepo (if not exists) [Token Method]"
  import_tasks: "config-root-repo-token.yaml"
  when:
  - (root_repository_git_auth_type == "token")
  - (primary_cluster_machine is defined)
  - (primary_cluster_machine == true)
  - (has_root_repo_secret is defined)
  - (has_root_repo_secret == false)
  tags:
  - acm-root-repo
  - acm-root-repo-token-method

- name: "Create dependencies for RootRepo (if not exists) [SSH Method]"
  import_tasks: "config-root-repo-ssh.yaml"
  when:
  - (root_repository_git_auth_type == "ssh")
  - (primary_cluster_machine is defined)
  - (primary_cluster_machine == true)
  - (has_root_repo_secret is defined)
  - (has_root_repo_secret == false)
  tags:
  - acm-root-repo
  - acm-root-repo-ssh-method

- name: "Create dependencies for RootRepo (if not exists) [GCP GSA Method]"
  import_tasks: "config-root-repo-gcp-gsa.yaml"
  when:
  - (root_repository_git_auth_type == "gcpserviceaccount")
  - (primary_cluster_machine is defined)
  - (primary_cluster_machine == true)
  tags:
  - acm-root-repo
  - acm-root-repo-gcp-gsa-method

- name: Copy RootRepo Sync Config File
  template:
    src: root-sync.yaml.j2
    dest: "{{ acm_config_files }}/root-sync.yaml"
  when:
    - (primary_cluster_machine is defined)
    - (primary_cluster_machine == true)
  tags:
  - acm-root-repo
  - generate-root-sync

- name: "Test for Root Repo installed"
  include_tasks: kubectl-presence.yml
  vars:
    name: "{{ primary_root_sync_name }}"
    type: "RootSync"
    namespace: "config-management-system"
    kubeconfig: "{{ kubeconfig_shared_location }}"
    fact_name: "has_root_repo_installed"
  when:
    - (primary_cluster_machine is defined)
    - (primary_cluster_machine == true)
  tags:
  - acm-root-repo

- name: "Apply Root Repo configuration"
  shell: |
    kubectl apply -f {{ acm_config_files }}/root-sync.yaml
    sleep 10s # just enough for the API to pick up the changes, then wait can take over
    kubectl wait --for=condition=established --timeout=600s crd rootsyncs.configsync.gke.io
    exit $?
  environment:
    KUBECONFIG: "{{ kubeconfig_shared_location }}"
  retries: 10
  delay: 10
  register: root_apply_result
  until: root_apply_result.rc == 0
  when:
    - (primary_cluster_machine is defined)
    - (primary_cluster_machine == true)
    - (has_root_repo_installed == false)
  tags:
  - acm-root-repo

- name: "Wait for RootReconciler deployment to be ready"
  command:
    cmd: kubectl wait --for=condition=available --timeout=600s deployment.apps/root-reconciler-{{ primary_root_sync_name }} -n config-management-system
  environment:
    KUBECONFIG: "{{ kubeconfig_shared_location }}"
  retries: 5
  delay: 10
  register: root_recon_result
  until: root_recon_result.rc == 0
  when:
    - (primary_cluster_machine is defined)
    - (primary_cluster_machine == true)
    - (has_root_repo_installed == false)
  tags:
  - acm-root-repo

- name: "Wait on ExternalSecrets to be deployed coming from RootRepo"
  shell: |
    kubectl wait --for=condition=available --timeout=600s deployment.apps/external-secrets -n external-secrets
  retries: 60
  delay: 10
  register: external_secret_deployment
  until: external_secret_deployment.rc == 0
  environment:
    KUBECONFIG: "{{ kubeconfig_shared_location }}"
  when:
    - (primary_cluster_machine is defined)
    - (primary_cluster_machine == true)
  tags:
  - acm-root-repo
  - external-secret-install

- name: Setup Workload Identity for ACM Monitorin
  run_once: true
  command:
    cmd: gcloud iam service-accounts add-iam-policy-binding --role roles/iam.workloadIdentityUser --member "serviceAccount:{{ google_project_id }}.svc.id.goog[config-management-monitoring/default]" acm-monitoring-agent@{{ google_project_id }}.iam.gserviceaccount.com
  when:
    - (primary_cluster_machine is defined)
    - (primary_cluster_machine == true)
  tags:
  - acm-root-repo
  - acm-monitoring-config

- name: "Wait on ExternalSecrets to be deployed coming from RootRepo"
  command:
    cmd: kubectl annotate serviceaccount default iam.gke.io/gcp-service-account=acm-monitoring-agent@{{ google_project_id }}.iam.gserviceaccount.com --namespace config-management-monitoring --overwrite=true
  environment:
    KUBECONFIG: "{{ kubeconfig_shared_location }}"
  when:
    - (primary_cluster_machine is defined)
    - (primary_cluster_machine == true)
  tags:
  - acm-root-repo
  - acm-monitoring-config
