- name: "Check for presence of GSR GSA"
  ignore_errors: true
  shell: |
    export GSA_EXISTS=$(gcloud iam service-accounts list --filter=email~{{ root_repository_service_account_email }} --format="value(name)")
    if [[ -z "${GSA_EXISTS}" ]]; then
      exit 1
    fi
  args:
    executable: /bin/bash
  register: has_gsr_gsa
  changed_when: false
  failed_when:
    - has_gsr_gsa.rc > 0
  tags:
  - acm-root-repo-gcp-gsa-method

#### Setup WorkloadIdentity (supporting GSR)
# https://cloud.google.com/anthos-config-management/docs/how-to/installing-kubectl#google-service-account

- name: "Configure WorkloadIdentity for GSR GSA"
  shell: |
    gcloud iam service-accounts add-iam-policy-binding \
        --role roles/iam.workloadIdentityUser \
        --member "serviceAccount:{{ google_project_id }}.svc.id.goog[config-management-system/root-reconciler]" \
        {{ root_repository_service_account_email }}
  when:
  - has_gsr_gsa.rc == 0
  tags:
  - acm-root-repo-gcp-gsa-method
