###
### This file holds common SDS/CSI installation tasks
###
### All SDSs are installed using Cluster Trait Repo concept. CTR is a RootSync object located in a git-repo with the specific configurations
###   of the installation and configuration. CTRs can rely on a GCS bucket for backups and a Google Secret called {{ storage_provider_auth_secret }}
###

###
### 1. If no SDS-specific `git-creds` in k8s, set that up in Google Secrets Manager
### 2. If no GCS bucket for the SDS is created, create a new one
### 3. Apply CTR to cluster
###

###
### At this point, the SDS git-creds should have been created (either via Ansible or outside IaC setup)
###    The GCS bucket for SDS backup should also have been created

# Apply SDS CTR to cluster
- name: Create SDS file/folder location
  file:
    path: '{{ sds_config_files }}'
    state: directory
    mode: '0755'
  tags:
  - sds-common-setup
  - sds-cluster-trait-repo

# TODO: Add a parameter to skip install of SDS Cluster Trait Repo (allowing setup of OS/dependencies, but skip the actual install)
- name: Copy SDS Cluster Trait Repo Config
  template:
    src: sds-cluster-trait-repo.yaml.j2
    dest: "{{ sds_config_files }}/sds-cluster-trait-repo.yaml"
  when:
  - storage_cluster_trait_repo_install == true
  tags:
  - sds-common-setup
  - sds-cluster-trait-repo

- name: "Apply SDS Cluster Trait Repo"
  shell: |
    kubectl apply -f {{ sds_config_files }}/sds-cluster-trait-repo.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig_shared_location }}"
  when:
  - (primary_cluster_machine is defined)
  - (primary_cluster_machine == true)
  - storage_cluster_trait_repo_install == true
  tags:
  - sds-common-setup
  - sds-cluster-trait-repo