# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

###
### This sub-role verifies the backup bucket for Longhorn, sets up the HMAC for communication with bucket and creates a ConfigMap with configuration specific to the cluster (not appropriate to put into ACM repos)
###

- name: Copy Longhorn namespace and configmap
  template:
    src: longhorn-default-setting.yml.j2
    dest: "{{ sds_config_files }}/longhorn-default-setting.yml"
  tags:
  - longhorn-config-management
  - longhorn-install

- name: Create Longhorn namespace and configmap
  command:
    cmd: kubectl apply -f {{ sds_config_files }}/longhorn-default-setting.yml
  when:
  - (primary_cluster_machine is defined)
  - (primary_cluster_machine == true)
  retries: "{{ default_retry_count }}"
  delay: "{{ default_retry_delay }}"
  register: cmc_result
  until: cmc_result.rc == 0
  environment:
    KUBECONFIG: "{{ kubeconfig_shared_location }}"
  tags:
  - longhorn-config-management
