###
### This sub-role verifies the backup bucket for Longhorn, sets up the HMAC for communication with bucket and creates a ConfigMap with configuration specific to the cluster (not appropriate to put into ACM repos)
###

- name: Copy Longhorn namespace and configmap
  template:
    src: longhorn-default-setting.yml.j2
    dest: "{{ sds_config_files }}/longhorn-default-setting.yml"
  when:
  - (primary_cluster_machine is defined)
  - (primary_cluster_machine == true)
  tags:
  - longhorn-config-management
  - longhorn-install

- name: Create Longhorn namespace and configmap
  command:
    cmd: kubectl apply -f {{ sds_config_files }}/longhorn-default-setting.yml
  when:
  - (primary_cluster_machine is defined)
  - (primary_cluster_machine == true)
  retries: "{{ default_retry_count }}"
  delay: "{{ default_retry_delay }}"
  register: cmc_result
  until: cmc_result.rc == 0
  environment:
    KUBECONFIG: "{{ kubeconfig_shared_location }}"
  tags:
  - longhorn-config-management
