- name: "Create secret for External Secrets"
  shell: |
    kubectl create ns external-secrets || true
    kubectl create secret generic gcp-store-creds --from-file=/var/keys/external-secrets-k8s-creds.json -n external-secrets || true
    kubectl label secret gcp-store-creds -n external-secrets type=gcpsm --overwrite
  ignore_errors: yes
  environment:
    KUBECONFIG: "{{ kubeconfig_shared_location }}"
  when:
    - (primary_cluster_machine is defined)
    - (primary_cluster_machine == true)
  tags:
  - external-secrets-secret
  - external-secrets

- name: Create folder for External Secrets files
  file:
    path: '{{ external_secrets_files }}'
    state: directory
    mode: '0755'
  tags:
  - external-secrets-operator
  - external-secrets

# Copy over the external secrets operator and CRD to all inventory
- name: Copy External Secrets Operator and CRD files
  copy:
    src: "{{ item }}"
    dest: "{{ external_secrets_files }}"
    mode: '0444' # read/write/execute owner, everyone else read/execute
  with_fileglob: "external-secrets-c*.yaml"
  tags:
  - external-secrets-operator
  - external-secrets

- name: "Install External Secrets Operator (b/185519826)"
  shell: |
      kubectl apply -f {{ external_secrets_files }}/external-secrets-crd.yaml
      # Allow for the API to register the API
      sleep 5s
      kubectl wait --for=condition=established --timeout=600s crd externalsecrets.external-secrets.io
      exit $?
  args:
    executable: /bin/bash
  environment:
    KUBECONFIG: "{{ kubeconfig_shared_location }}"
  when:
    - (primary_cluster_machine is defined)
    - (primary_cluster_machine == true)
  retries: 3
  register: result
  until: result.rc == 0
  tags:
  - external-secrets-operator
  - external-secrets

- name: Copy Secrets Manager Store
  template:
    src: external-secrets-store.yaml.j2
    dest: "{{ external_secrets_files }}/external-secrets-store.yaml"
  when:
    - (primary_cluster_machine is defined)
    - (primary_cluster_machine == true)
  tags:
  - external-secrets
  - external-secrets-store

- name: "Install External Secrets Operator (b/185519826)"
  shell: |
      kubectl apply -f {{ external_secrets_files }}/external-secrets-store.yaml
  args:
    executable: /bin/bash
  environment:
    KUBECONFIG: "{{ kubeconfig_shared_location }}"
  when:
    - (primary_cluster_machine is defined)
    - (primary_cluster_machine == true)
  retries: 3
  register: result
  until: result.rc == 0
  tags:
  - external-secrets-store
  - external-secrets
