#
# Install ACM
# Setup Root Repository
#
- name: Folder for ACM configurations
  file:
    path: '{{ config_files }}'
    state: directory
    mode: '0755'
  tags:
  - abm-install
  - abm-config

- name: "Enable ACM"
  command:
    cmd: gcloud alpha container hub config-management enable
  run_once: true
  environment:
    PATH: "{{ tools_base_path }}/google-cloud-sdk/bin:{{ ansible_env.PATH }}"
    GOOGLE_APPLICATION_CREDENTIALS: "/var/keys/gsa-key.json"
  tags:
  - abm-software
  - enable-acm

- name: "Install ACM"
  shell: |
      # Install ACM (Config Management base operator)
      gsutil cp gs://config-management-release/released/{{ acm_version }}/config-management-operator.yaml {{ config_files }}/config-management-operator.yaml

      kubectl apply -f {{ config_files }}/config-management-operator.yaml
  args:
    executable: /bin/bash
    creates: /var/nothing
  environment:
    PATH: "{{ tools_base_path }}/google-cloud-sdk/bin:{{ ansible_env.PATH }}"
    GOOGLE_APPLICATION_CREDENTIALS: "/var/keys/gsa-key.json"
    KUBECONFIG: "{{ kubeconfig_shared_location }}"
  tags:
  - abm-software
