# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### Create Local PVC folder (future will be mounted or something)
- name: Create ncgctl folder
  file:
    path: "{{ tools_base_path }}/ncgctl-{{ ncgctl_version }}"
    state: directory
    mode: '0755'
  tags:
  - ncg-install
  - post-acm

- name: "Install Network Connectivity CRDs"
  shell: |
    {{ tools_base_path }}/ncgctl-{{ ncgctl_version }}/bin/ncgctl --enable-ncg-on-existing-cluster
    {{ tools_base_path }}/ncgctl-{{ ncgctl_version }}/bin/ncgctl --verify
    {{ tools_base_path }}/ncgctl-{{ ncgctl_version }}/bin/ncgctl --install --kubeconfig "{{ kubeconfig_shared_location }}"
  args:
    chdir: "{{ tools_base_path }}/ncgctl-{{ ncgctl_version }}"
    executable: /bin/bash
  environment:
    KUBECONFIG: "{{ kubeconfig_shared_location }}"
  when:
  - (primary_cluster_machine is defined)
  - (primary_cluster_machine == true)
  retries: "{{ default_retry_count }}"
  delay: "{{ default_retry_delay }}"
  tags:
  - ncg-install
  - post-acm

- name: "Hydrate and copy Network Connectivity Gateway templates"
  template:
    src: "{{ item.template }}"
    dest: "{{ acm_config_files }}/{{ item.final_name }}"
  loop:
  - {"template": "overlay-vpn-tunnel.yaml.j2", "final_name": "overlay-vpn-tunnel.yaml"}
  - {"template": "overlay-vpn-bgp-peer.yaml.j2", "final_name": "overlay-vpn-bgp-peer.yaml"}
  tags:
  - ncg-install
  - post-acm

- name: "Apply Network Connectivity Gateway Configurations"
  shell: |
    kubectl apply -f {{ acm_config_files }}/{{ item.final_name }}
  environment:
    KUBECONFIG: "{{ kubeconfig_shared_location }}"
  loop:
  - {"final_name": "overlay-vpn-tunnel.yaml"}
  - {"final_name": "overlay-vpn-bgp-peer.yaml"}
  when:
  - primary_cluster_machine is defined
  - primary_cluster_machine == true
  tags:
  - ncg-install
  - post-acm
