
- name: "Hydrate and copy templates Anthos Network Gateway"
  template:
    src: "{{ item.template }}"
    dest: "{{ acm_config_files }}/{{ item.final_name }}"
  loop:
  - {"template": "network-gateway-group.yaml.j2", "final_name": "network-gateway-group.yaml"}
  - {"template": "ang-multi-cluster-connect-config.yaml.j2", "final_name": "ang-multi-cluster-connect-config.yaml"}
  - {"template": "egress-nat-config.yaml.j2", "final_name": "egress-nat-config.yaml"}
  when:
  - primary_cluster_machine is defined
  - primary_cluster_machine == true
  tags:
  - ang-install
  - post-acm

- name: "Create IKE secret"
  shell: |
    kubectl create secret -n kube-system generic ike-key --from-literal=psk={{ ike_key_secret_value }} || true
  environment:
    KUBECONFIG: "{{ kubeconfig_shared_location }}"
  when:
  - primary_cluster_machine is defined
  - primary_cluster_machine == true
  tags:
  - ang-install
  - post-acm

- name: "Apply ANG Configurations"
  shell: |
    kubectl apply -f {{ acm_config_files }}/{{ item.final_name }}
  environment:
    KUBECONFIG: "{{ kubeconfig_shared_location }}"
  loop:
  - {"template": "network-gateway-group.yaml.j2", "final_name": "network-gateway-group.yaml"}
  - {"template": "ang-multi-cluster-connect-config.yaml.j2", "final_name": "ang-multi-cluster-connect-config.yaml"}
  - {"template": "egress-nat-config.yaml.j2", "final_name": "egress-nat-config.yaml"}
  when:
  - primary_cluster_machine is defined
  - primary_cluster_machine == true
  tags:
  - ang-install
  - post-acm
