---
# tasks file for abm-install

## TODO: Move this to "ready-ubuntu"
  - name: Create a user for ABM Control
    ansible.builtin.user:
      name: "{{ abm_install_user }}"
      shell: /bin/bash
      groups: "sudo"
      append: yes
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/{{ ssh_key_name }}
    tags:
    - abm-install
    - abm-ssh

## Setup password less SSH into same box
  - name: "Place ssh config with no-host-check turned on"
    template:
      src: ssh-config.j2
      dest: "{{ ssh_user_home }}/config"
      group: "{{ abm_install_user }}"
      owner: "{{ abm_install_user }}"
    tags:
    - abm-install
    - abm-ssh

### Add the new user to the no-password sudoers list
  - name: Add user to sudoers list
    template:
      src: sudoers.j2
      dest: "/etc/sudoers.d/{{ abm_install_user }}"
    tags:
    - abm-install
    - abm-ssh

### cat {{ ssh_key_path }}.pub >> {{ ssh_user_home }}/authorized_keys
  - name: Set authorized key taken from file
    shell: |
      # remove existing authorized_keys
      rm -rf {{ ssh_user_home }}/authorized_keys || true
      touch {{ ssh_user_home }}/authorized_keys
      cat {{ ssh_key_path_pub }} >> {{ ssh_user_home }}/authorized_keys
      # make files user access only
      chown {{ abm_install_user }}.{{ abm_install_user }} {{ ssh_user_home }}/authorized_keys
      # SSH Key itself, make only read/write from current user
      chmod 400 {{ ssh_key_path }}
    args:
      executable: /bin/bash
      creates: /var/nothing
    tags:
    - abm-install
    - abm-ssh

### Create or enable Google Service Accounts
  - name: Create or Enable Service Accounts
    shell: |
          SA_NAME="{{ item.name }}"
          PROJECT="{{ google_project_id }}"
          DESCRIPTION="{{ item.description }}"
          CURR_SA_NAME=$(gcloud iam service-accounts describe ${SA_NAME}@${PROJECT}.iam.gserviceaccount.com --format="value(name)" 2> /dev/null)
          if [ -z "$CURR_SA_NAME" ]; then
              gcloud iam service-accounts create ${SA_NAME} --display-name "${DESCRIPTION}"
          else
              gcloud iam service-accounts enable "${SA_NAME}@${PROJECT}.iam.gserviceaccount.com"
          fi
    loop: "{{ service_accounts }}"
    run_once: true # only one machine to do this
    args:
      executable: /bin/bash
      creates: /var/nothing
    environment:
      PATH: "{{ tools_base_path }}/google-cloud-sdk/bin:{{ ansible_env.PATH }}"
      GOOGLE_APPLICATION_CREDENTIALS: "/var/keys/gsa-key.json"
    tags:
    - abm-install
    - abm-once

  - name: Add roles to service accounts
    command:
      cmd: gcloud projects add-iam-policy-binding {{ google_project_id }} --member="serviceAccount:{{ item.0.name }}@{{ google_project_id }}.iam.gserviceaccount.com" --role="{{ item.1 }}"
    loop: "{{ service_accounts | subelements('roles') }}"
    run_once: true
    environment:
      PATH: "{{ tools_base_path }}/google-cloud-sdk/bin:{{ ansible_env.PATH }}"
      GOOGLE_APPLICATION_CREDENTIALS: "/var/keys/gsa-key.json"
    tags:
    - abm-install
    - abm-once

### Check if the GSA keys exists in Secrets Manager
  - name: "Look to see if GSA keys exists in secrets manager"
    run_once: true # only one machine to do this
    shell: |
      export HAS_SECRET=$(gcloud secrets list --filter="name~{{ item.name }}" --format="value(name)" --project="{{ google_project_id }}")
      if [ -z "$HAS_SECRET" ]; then
        gcloud secrets create {{ item.name }} --replication-policy="automatic" --project={{ google_project_id }}
        echo "NO SECRET {{ item.name }}"
        exit 1 # exit early, no chance there's a version since there wasn't a secret
      fi

      gcloud secrets versions access latest --secret="{{ item.name }}" --project="{{ google_project_id }}" &>/dev/null
      if [ $? -gt 0 ]; then
        echo "NO SECRET {{ item.name }}"
        exit 1
      fi
    args:
      executable: /bin/bash
    register: secret_exists
    changed_when: "'NO SECRET' in secret_exists.stdout"
    ignore_errors: true
    loop: "{{ service_accounts }}"
    environment:
      PATH: "{{ tools_base_path }}/google-cloud-sdk/bin:{{ ansible_env.PATH }}"
      GOOGLE_APPLICATION_CREDENTIALS: "/var/keys/gsa-key.json"
    tags:
    - abm-once
    - abm-debug
    - abm-gsa-keys
    - abm-install

  - name: Create new GSA keys for all service accounts in configuration and push to Secret Manager
    run_once: true # only one machine to do this
    shell: |
      gcloud iam service-accounts keys create /tmp/{{ entry.item.keyfile }} --iam-account={{ entry.item.name }}@{{ google_project_id }}.iam.gserviceaccount.com --project={{ google_project_id }}
      gcloud secrets versions add {{ entry.item.name }} --data-file="/tmp/{{ entry.item.keyfile }}"
      rm -rf /tmp/{{ entry.item.keyfile }} # delete temp file
    args:
      executable: /bin/bash
    when: entry.rc != 0
    loop: "{{ secret_exists.results }}"
    loop_control:
      loop_var: entry
    environment:
      PATH: "{{ tools_base_path }}/google-cloud-sdk/bin:{{ ansible_env.PATH }}"
      GOOGLE_APPLICATION_CREDENTIALS: "/var/keys/gsa-key.json"
    tags:
    - abm-once
    - abm-debug
    - abm-gsa-keys
    - abm-install

  - name: Write GSA key files from secret manager
    shell: |
      gcloud secrets versions access latest --secret="{{ item.name }}" >> {{ remote_gsa_key }}/{{ item.keyfile }}
    args:
      executable: /bin/bash
      creates: "{{ remote_gsa_key }}/{{ item.keyfile }}"
    loop: "{{ service_accounts }}"
    environment:
      PATH: "{{ tools_base_path }}/google-cloud-sdk/bin:{{ ansible_env.PATH }}"
      GOOGLE_APPLICATION_CREDENTIALS: "/var/keys/gsa-key.json"
    tags:
    - abm-once
    - abm-debug
    - abm-gsa-keys
    - abm-install

### Create Local PVC folder (future will be mounted or something)
  - name: Create PVC Folder
    file:
      path: '{{ local_pvc_mount }}'
      state: directory
      mode: '0755'
    tags:
    - abm-install
    - abm-config

### Create install folder
  - name: Create isolated install folder
    file:
      path: '{{ abm_workspace_folder }}/{{ cluster_name }}'
      state: directory
      mode: '0755'
    tags:
    - abm-install
    - abm-config

### Create configuration file (TODO: Switch this to a template)
  - name: "Place configuration file into ABM install folder"
    template:
      src: cluster-config.yaml.j2
      dest: "{{ abm_workspace_folder }}/{{ cluster_name }}/{{ cluster_name }}.yaml"
    tags:
    - abm-install
    - abm-config

### Check if cluster is installed already (kubeconfig file would exist)
  - name: Check to see if ABM has been installed already
    stat:
      path: "{{ abm_install_folder }}/bmctl-workspace/{{ cluster_name }}/{{ cluster_name }}-kubeconfig"
    register: abm_installed
    tags:
    - abm-install
    - abm-create

### Check cluster configuration
  - name: Validate configuration file updates
    command:
      cmd: bmctl check config --cluster={{ cluster_name }}
    args:
      chdir: "{{ abm_install_folder }}"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/var/keys/gsa-key.json"
    when:
      - abm_installed.stat.exists == False
    tags:
    - abm-install
    - abm-config

### Create cluster configuration
  - name: "Create cluster {{ cluster_name }} -- (be patient, this takes 20-40 minutes)"
    command: bmctl create cluster --cluster={{ cluster_name }}
    args:
      chdir: "{{ abm_install_folder }}"
      creates: "{{ abm_install_folder }}/bmctl-workspace/{{ cluster_name }}/{{ cluster_name }}-kubeconfig"
    async: 3600 # run for up to 60 minutes
    #poll: 30 # poll status every 30 seconds
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/var/keys/gsa-key.json"
    tags:
    - abm-install
    - abm-create

### TODO: Add a "if fails" then remove the cluster `bmctl reset -c {{ cluster_name }}`

#### Post Install Activities
  - name: Create PVC Folder
    file:
      path: '{{ kubeconfig_shared_root }}'
      state: directory
      mode: '0755'
    tags:
    - abm-install
    - abm-post-install

  - name: "Setup profile.d for kubeconfig"
    template:
      src: profile-user.sh.j2
      dest: "/etc/profile.d/kubeconfig.sh"
    tags:
    - abm-install
    - abm-post-install

  - name: Set insecure permissions to allow kubens to modify configuration when not root
    ansible.builtin.file:
      path: "{{ abm_install_folder }}/bmctl-workspace/{{ cluster_name }}/{{ cluster_name }}-kubeconfig"
      mode: '0666' # allow read/write to all (yes, this is maybe not great, but useful for kubens)
    tags:
    - abm-post-install
    - abm-install

  - name: Symbolic link to kubeconfig
    ansible.builtin.file:
      src: "{{ abm_install_folder }}/bmctl-workspace/{{ cluster_name }}/{{ cluster_name }}-kubeconfig"
      dest: "{{ kubeconfig_shared_location }}"
      group: sudo
      state: link
    tags:
    - abm-post-install
    - abm-install

# DONE