---
# tasks file for abm-install

  - name: Create configuration file
    shell: |
        gcloud config configurations list
        exit $?
    args:
      executable: /bin/bash
    register: gcloud
    environment:
        PATH: "{{ tools_base_path }}/google-cloud-sdk/bin:{{ ansible_env.PATH }}"
        GOOGLE_APPLICATION_CREDENTIALS: "/var/keys/gsa-key.json"

  - name: output of gcloud
    debug:
      msg: "{{ gcloud.stdout }}"

### Create install folder
  - name: Create isolated install folder
    file:
      path: '{{ abm_install_folder }}'
      state: directory
      mode: '0755'

  - name: Create configuration file
    command:
      cmd: bmctl create config -c {{ cluster_name }} --enable-apis --create-service-accounts --project-id={{ google_project_id }}
      creates: "{{ abm_install_folder }}/bmctl-workspace/{{ cluster_name }}/{{ cluster_name }}.yaml"
    args:
      chdir: "{{ abm_install_folder }}"
    retries: 5
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/var/keys/gsa-key.json" # UGH, Ansible SUCKS!!!  Interactive shell doesn't pick up existing ENV variables

  # - name: Validate configuration file updates
  #   command: bmctl check config --cluster={{ cluster_name }} # Does not work
  #   args:
  #     chdir: "{{ abm_install_folder }}"
  #   environment:
  #     GOOGLE_APPLICATION_CREDENTIALS: "/var/keys/gsa-key.json"

  - name: Store or do something with kubeconfig
    debug:
      msg: "do something with the config -- kubectl --kubeconfig bmctl-workspace/cluster1/cluster1-kubeconfig get nodes"

# DONE