## This shares the primary's kubeconfig with the other's in the cluster

- name: Create folder for kubeconfig
  ansible.builtin.file:
    path: "{{ kubeconfig_shared_root }}"
    state: "directory"
    mode: '0774'
    group: sudo
    owner: "{{ abm_install_user }}"
  tags:
  - abm-post-install
  - abm-install
  - kubeconfig-share

- name: Symbolic link for primary machines
  ansible.builtin.file:
    src: "{{ abm_install_folder }}/bmctl-workspace/{{ cluster_name }}/{{ cluster_name }}-kubeconfig"
    dest: "{{ kubeconfig_shared_location }}"
    state: link
    mode: '0666'
  when: "(primary_cluster_machine is defined) and (primary_cluster_machine == true)"
  tags:
  - abm-post-install
  - abm-install
  - kubeconfig-share

# Copy the kubeconfig to local via primary machine
- name: Copy generated kubeconfig to other in cluster
  become_user: "{{ abm_install_user }}"
  command:
    cmd: "scp {{ abm_install_folder }}/bmctl-workspace/{{ cluster_name }}/{{ cluster_name }}-kubeconfig {{ abm_install_user }}@{{ machine }}:{{ kubeconfig_shared_location }}"
  loop: "{{ control_plane_ips }}"
  loop_control:
    loop_var: machine
  when:
    - primary_cluster_machine is defined
    - primary_cluster_machine == True
    - control_plane_ip != machine
  tags:
  - abm-post-install
  - abm-install
  - kubeconfig-share
  - kube-share

- name: Set permissions to edit for all
  ansible.builtin.file:
    path: "{{ kubeconfig_shared_location }}"
    mode: '0666'
    follow: yes
  tags:
  - abm-post-install
  - abm-install
  - kubeconfig-share