
---

# Installs Anthos Bare Metal on inventory of "workers"
# must specify `--tags never` on the CLI to run this
- hosts: cloud_type_abm
  become: true
  become_user: root
  roles:
    - abm-remove
  vars: []