
---

# Setup a baseline for all servers
# Setup tools
# gcloud
# gsutil
# kubectl
# bmctl
# Docker and container.d
- hosts: all
  become: true
  become_user: root
  roles:
    - common
    - google-tools
    - ready-ubuntu


# Provision KVM and 3 VMs

# Setup KVM network

# Install ABM

# Validate ABM