
---

- hosts: workers
  become: true
  become_user: root
  roles:
    # - google-tools
    - abm-install
  vars:
    # Initial project ID to setup gcloud with
    - google_project_id: "{{ lookup('env', 'PROJECT_ID') }}"
    - google_region: "{{ lookup('env', 'REGION') | default('us-central1', True) }}"
    - google_zone: "{{ lookup('env', 'ZONE') | default('us-central1-a', True) }}"

    # Scratch directory for tool installation
    - tools_base_path: "/var/google-tools-install"