
---

# Installs Anthos Bare Metal on inventory of "workers"
- hosts: cloud_type_abm
  become: true
  become_user: root
  roles:
    # - abm-install
    - abm-software
    - abm-login-token
  vars: []
