
# Runs apt-get update & apt-get upgrade (and some other tools like gcloud update) on ALL inventory

- hosts: workers
  become: true
  become_user: root
  gather_facts: false
  pre_tasks:
  - name: Decrypt SSH key
    include_role:
      name: decrypt-ssh-key
  - name: Gathering Facts
    setup: {}
  roles:
    - update
  vars: []
  tags:
  - hardware

- hosts: cloud_type_abm
  become: true
  become_user: root
  pre_tasks:
  - name: Decrypt SSH key
    include_role:
      name: decrypt-ssh-key
  - name: Gathering Facts
    setup: {}
  roles:
    - update
  vars: []
  tags:
  - cloud
