
- hosts: workers
  gather_facts: false
  pre_tasks:
  - name: Decrypt SSH key
    include_role:
      name: decrypt-ssh-key
  - name: Gathering Facts
    setup: {}
  roles:
    - abm-login-token
  vars:
    kubeconfig_shared_location: "/var/kubeconfig/kubeconfig"
  tags:
    - hardware

- hosts: cloud_type_abm
  roles:
    - abm-login-token
  vars:
    kubeconfig_shared_location: "/var/kubeconfig/kubeconfig"
  tags:
    - cloud
