
---

# Installs Anthos Bare Metal on inventory of "workers"
- hosts: workers
  become: true
  become_user: root
  roles:
    - validate
    - google-tools
    - ready-ubuntu
    - setup-kvm
    - abm-install
    - abm-software
    - abm-login-token
  vars: []
