---
- name: Converge
  hosts: all
  tasks:
    - name: "Provision gcloud tools"
      include_role:
        name: "google-tools"
    - name: "Include abm-install"
      include_role:
        name: "abm-install"
