---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: buster
    image: docker.io/python:3.9.1-buster
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
