# Used for logging/metrics
machine_label: "cnuc-1"

# This machine's IP
node_ip: "10.200.0.2"

# Indicates that this is the primary machine in the cluster (only important for provisioning)
primary_cluster_machine: true
