
## Vars specifically for CNUC2

cluster_name: "cnuc-2"
#cluster_index: 10
acm_cluster_name: "store-5-1"
control_plane_ip: "10.200.0.2" # inside vlan 42
control_plane_vip: "10.200.0.49"
ingress_vip: "10.200.0.50"
load_balancer_pool_cidr: "10.200.0.50-10.200.0.70"
