
## Vars specifically for CNUC4

# Name of the cluster
cluster_name: "cnuc-7"
# Used for logging/metrics
machine_label: "cnuc-7"

# Indicates that this is the primary machine in the cluster (only important for provisioning)
primary_cluster_machine: true
# Name of the "store" per the ACM repo
acm_cluster_name: "{{ lookup('env', 'CLUSTER_ACM_NAME') | default('location-5', True) }}"

# This machine's IP
control_plane_ip: "10.200.0.2"
# The other IPs in the cluster
control_plane_ips: [
  "10.200.0.2",
  "10.200.0.3",
  "10.200.0.4"
]
# KubeAPI IP address
control_plane_vip: "10.200.0.49"
# Ingress (k8s) address, must be in LoadBalancer pool below
ingress_vip: "10.200.0.50"

# Load balancers created in this range
load_balancer_pool_cidr: [
  "10.200.0.50-10.200.0.70"
]

# Ansible Pull Authenticaiton String
ansible_pull_authentication_string: "{{scm_token_user}}:{{scm_token_token}}@"

# Ansible Pull repo for Remote Execution
ansible_pull_remote_execute_repo: "https://{{ ansible_pull_authentication_string | default('', true) }}gitlab.com/gcp-solutions-public/retail-edge/remote-command-repo.git"

# Ansible pull repo to manage simplified drift
ansible_pull_drift_repo: "https://{{ ansible_pull_authentication_string | default('', true) }}gitlab.com/gcp-solutions-public/retail-edge/drift-repo.git"