
# Name of the cluster
cluster_name: "edge-1"
# Used for logging/metrics
machine_label: "edge-1"
# Indicates that this is the primary machine in the cluster (only important for provisioning)
primary_cluster_machine: true
# Name of the "store" per the ACM repo
acm_cluster_name: "{{ lookup('env', 'CLUSTER_ACM_NAME') | default('edge-1', True) }}"
# This machine's IP
control_plane_ip: "192.168.3.10"
# The other IPs in the cluster
control_plane_ips: [
  "192.168.3.10",
  "192.168.3.11",
  "192.168.3.12"
]
# KubeAPI IP address
control_plane_vip: "192.168.3.100"
# Ingress (k8s) address, must be in LoadBalancer pool below
ingress_vip: "192.168.3.20"
# Load balancers created in this range
load_balancer_pool_cidr: [
  "192.168.3.20-192.168.3.30" # 9 IPs for LB + 1 Ingress
]