cluster_name: "nuc-4"
cluster_index: 3
location_primary: true
acm_cluster_name: "store-2-1"
control_plane_ip: "192.168.1.14"
control_plane_vip: "192.168.1.130"
ingress_vip: "192.168.1.131"
load_balancer_pool_cidr: "192.168.1.131-192.168.1.139"
