
# Home directory for ACM download and operations
acm_config_files: "/var/acm-configs"

# Home directory for external secrets download and operations
external_secrets_files: "/var/external-secrets"

root_repository_branch: "main"
root_repository_policy_dir: "/config"
root_repository_git_auth_type: "token"
# NOTE: This is a tight coupling with the "Root Repo" that contains "ExternalSecret" instances with the `git-creds` name
#       IF changed, both the ACM root-repo and this field need to match
root_repository_git_secret_name: "git-creds"
