
acm_version: "latest"

kubeconfig_shared_root: "/var/kubeconfig"
kubeconfig_shared_location: "{{ kubeconfig_shared_root }}/kubeconfig"

acm_config_files: "/var/acm-configs"

root_repository_policy_dir: "/config"