
# Home directory for ACM download and operations
acm_config_files: "/var/acm-configs"

# Home directory for external secrets download and operations
external_secrets_files: "/var/external-secrets"

root_repository_branch: "main"
root_repository_policy_dir: "/config"
root_repository_git_auth_type: "token"
# NOTE: This is a tight coupling with the "Root Repo" that contains "ExternalSecret" instances with the `git-creds` name
#       IF changed, both the ACM root-repo and this field need to match
root_repository_git_secret_name: "git-creds"

# This is the production project that contains the CDI containers. Need it to replace with the staging dynamically in file
cdi_staging_project: "anthos-baremetal-release"

# Folder to run installation out of
abm_install_folder: "/var/abm-install"

# CDI add CPU Monitoring flag script run by cron.d
cdi_cron_script_file: "/var/cdi-check-node.sh"

# OIDC config vars
enable_oidc: true
oidc_client_id: "{{ lookup('env', 'OIDC_CLIENT_ID') }}"
oidc_client_secret: "{{ lookup('env', 'OIDC_CLIENT_SECRET') }}"
oidc_user: "{{ lookup('env', 'OIDC_USER') }}"