
# gsutil ls -al gs://config-management-release/released/
acm_version: "1.6.2"

kubeconfig_shared_root: "/var/kubeconfig"
kubeconfig_shared_location: "{{ kubeconfig_shared_root }}/kubeconfig"

acm_config_files: "/var/acm-configs"

root_repository_branch: "main"
root_repository_policy_dir: "/config"
root_repository_git_auth_type: "token"
root_repository_git_secret_name: "git-creds"
