---
# vars file for abm-install

abm_version: "1.7.0"

# Folder to run installation out of
abm_install_folder: "/var/abm-install"
abm_workspace_folder: "{{ abm_install_folder }}/bmctl-workspace"

# Match with Google-Tools (by convention, not required, but good idea)
remote_gsa_key: "/var/keys"
ssh_key_path: /root/.ssh/abm_rsa

# Cluster Configuration
install_type: standalone
pod_cidr: "172.2.0.0/16"
services_1_cidr: "10.96.0.0/24"
control_plane_vip: "192.168.86.241"
ingress_vip: "192.168.86.245" # must be in LB pool
load_balancer_pool_cidr: "192.168.86.245-192.168.86.254" # cannot overlap with control_plane_vip

enable_application_logging: false

local_pvc_mount: "/opt/pvc-disk"

control_plane_ip: [
  "{{ lookup('dig', 'store-1.lan') }}",
  "{{ lookup('dig', 'store-2.lan') }}",
  "{{ lookup('dig', 'store-3.lan') }}",
  "{{ lookup('dig', 'store-4.lan') }}",
  "{{ lookup('dig', 'store-5.lan') }}"
]

# Service Account Configuration
service_accounts: [
  {
    name: abm-gcr-agent,
    keyfile: abm-gcr-agent-creds.json,
    description: "ABM GCR Agent Account",
    roles: [
      "roles/storage.objectViewer"
    ]
  },
  {
    name: abm-gke-connect-agent,
    keyfile: abm-gke-connect-agent-creds.json,
    description: "ABM GKE Connect Agent Service Account",
    roles: [
      "roles/gkehub.connect"
    ]
  },
  {
    name: abm-gke-register-agent,
    keyfile: abm-gke-register-agent-creds.json,
    description: "ABM GKE Connect Register Account",
    roles: [
      "roles/gkehub.admin"
    ]
  },
  {
    name: abm-cloud-operations-agent,
    keyfile: abm-cloud-operations-agent-creds.json,
    description: "ABM Cloud Operations Service Account",
    roles: [
      "roles/logging.logWriter",
      "roles/monitoring.metricWriter",
      "roles/stackdriver.resourceMetadata.writer",
      "roles/monitoring.dashboardEditor"
    ]
  }
]
