---
# vars file for abm-install

# GCP Project to associate with
google_project_id: "{{ lookup('env', 'PROJECT_ID') }}"

# Folder to run installation out of
abm_install_folder: "/var/abm-install"


## In the future, setup these to be in an object or something
control_plane_1_ip: "{{ lookup('dig', 'nuc-1.lan') }}"

pod_1_cidr: "192.168.0.0/16"
services_1_cidr: "192.168.86.0/12" # 10.96.0.0/12 <-- orig value, new needs to be in VIP range
enable_application_logging_1: false

control_plane_2_ip: "{{ lookup('dig', 'nuc-2.lan')}"
control_plane_3_ip: "{{ lookup('dig', 'nuc-3.lan')}"
control_plane_4_ip: "{{ lookup('dig', 'nuc-4.lan')}"
control_plane_5_ip: "{{ lookup('dig', 'nuc-5.lan')}"