---
# vars file for abm-install

# # GCP Project to associate with
# google_project_id: "{{ lookup('env', 'PROJECT_ID') }}"
# google_region: "{{ lookup('env', 'REGION') | default('us-central1', True) }}"
# google_zone: "{{ lookup('env', 'ZONE') | default('us-central1-a', True) }}"

# Folder to run installation out of
abm_install_folder: "/var/abm-install"
abm_workspace_folder: "{{ abm_install_folder }}/bmctl-workspace"

# Match with Google-Tools (by convention, not required, but good idea)
remote_gsa_key: "/var/keys"
sshPrivateKeyPath: /root/.ssh/id_rsa

# Cluster Configuration
install_type: standalone
pod_cidr: "192.168.0.0/16"
services_1_cidr: "10.96.0.0/12" #  "192.168.86.0/12" (what network is this supposed to be in?)
control_plane_vip: "10.0.0.8"
ingress_vip: "10.0.0.10" # must be in LB pool
load_balancer_pool_cidr: "10.0.0.10-10.0.0.254" # cannot overlap with control_plane_vip

enable_application_logging_1: false

control_plane_ip: [
  "{{ lookup('dig', 'store-1.lan') }}",
  "{{ lookup('dig', 'store-2.lan') }}",
  "{{ lookup('dig', 'store-3.lan') }}",
  "{{ lookup('dig', 'store-4.lan') }}",
  "{{ lookup('dig', 'store-5.lan') }}"
]

# Service Account Configuration
service_accounts: [
  {
    name: abm-gcr-agent,
    keyfile: abm-gcr-agent-creds.json,
    description: "ABM GCR Agent Account",
    roles: [
      "roles/storage.objectViewer"
    ]
  },
  {
    name: abm-gke-connect-agent,
    keyfile: abm-gke-connect-agent-creds.json,
    description: "ABM GKE Connect Agent Service Account",
    roles: [
      "roles/gkehub.connect"
    ]
  },
  {
    name: abm-gke-register-agent,
    keyfile: abm-gke-register-agent-creds.json,
    description: "ABM GKE Connect Register Account",
    roles: [
      "roles/gkehub.admin"
    ]
  },
  {
    name: abm-cloud-operations-agent,
    keyfile: abm-cloud-operations-agent-creds.json,
    description: "ABM Cloud Operations Service Account",
    roles: [
      "roles/logging.logWriter",
      "roles/monitoring.metricWriter",
      "roles/stackdriver.resourceMetadata.writer",
      "roles/monitoring.dashboardEditor"
    ]
  }
]
