# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# vars file for abm-install

# Edge API
edge_api_enabled: false
edge_api_location: us-central1 # same as cloud-ops region {{ google_region }}, but hard-coded as API is only in us-central1

# User that has sudo, password less SSH access to node_ip
abm_install_user: "el-gato"

# Cluster Configuration
install_type: standalone
multi_network_enabled: "{{ enable_multus_network | default('false', True) }}"

# Configure Customer Application's logging and metrics
# NOTE: CloudOPs + Google Managed Prometheus is the peferred method, but requires two parameters to be set. While not mutually exclusive, enabling both options is expensive and redundant
enable_stackdriver_customer_app_logging: false
# Use CloudOps to push customer logs (preferred) - NOTE: GMP and CloudOps should be enabled together (not required, but recommended)
enable_cloudops_customer_app_logging: true
# Use Google Managed Prometheus to push metrics (preferred)
enable_google_managed_prometheus_customer_app_metrics: true

# Skip preflight checks?
skip_preflight: false

# Cluster IP Ranges
pod_cidr: "172.16.0.0/16"
services_cidr: "192.168.30.0/23"

# Cluster Persistant Volumes (outside of overlay storage options)
local_pvc_mount: "/opt/pvc-disk"
local_share_pvc_mount: "/opt/localpv-share" # Default value

# Cluster runtime
container_runtime: "containerd" # docker or containerd

# How long to let the ABM installation (via bmctl) take before an Ansible timeout occurs. Default 120 min
abm_install_sync_timeout_seconds: 18000
abm_install_sync_poll_seconds: 60