---
# tasks file for ready-ubuntu

### Verify OS is approved (Ubuntu only at this point). Saves the pre-checks later
- name: Fail if not running on Ubuntu 18.04 or 20.04
  fail:
    msg: "This playbook can only run on Ubuntu 18.04 or 20.04. Using {{ ansible_distribution }}:{{ ansible_distribution_version }}"
  when: ansible_distribution != "Ubuntu" or (ansible_distribution_version != '18.04' and ansible_distribution_version != '20.04')

#### Stop and disable apparmor
- name: Stop apparmor
  systemd:
    state: stopped
    name: apparmor

- name: Disable apparmor
  systemd:
    name: apparmor
    enabled: no

#### Disable ufw
- name: Disable wfw
  command: ufw disable
  register: ufw

- name: Show output for firewall stopping
  debug:
    msg: "{{ ufw.stdout }}"

#### Setup Docker
- name: Remove all docker-based existing packages
  apt:
    pkg:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - run
    state: absent
  tags: docker

- name: Install Docker 19+ packages
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - docker.io
    state: present
    update_cache: yes
  tags: docker

- name: Get Docker version
  command: docker version
  register: docker
  tags: docker

- name: Show output with docker version
  debug:
    msg: "{{ docker.stdout }}"
  tags: docker

- name: Add the docker group (NOTE, users will need to be manually added with `usermod`)
  group:
    name: docker
    state: present
