---
# tasks file for ready-ubuntu

### Verify OS is approved (Ubuntu only at this point). Saves the pre-checks later
- name: Fail if not running on Ubuntu 18.04 or 20.04
  fail:
    msg: "This playbook can only run on Ubuntu 18.04 or 20.04. Using {{ ansible_distribution }}:{{ ansible_distribution_version }}"
  when: ansible_distribution != "Ubuntu" or (ansible_distribution_version != '18.04' and ansible_distribution_version != '20.04')
  tags:
  - verify

#### Stop and disable apparmor
- name: Stop apparmor
  systemd:
    state: stopped
    name: apparmor
  tags:
  - remove

- name: Disable apparmor
  systemd:
    name: apparmor
    enabled: no
  tags:
  - remove

#### Disable ufw
- name: Disable wfw
  command: ufw disable
  register: ufw
  tags:
  - remove

- name: Show output for firewall stopping
  debug:
    msg: "{{ ufw.stdout }}"
  tags:
  - remove
  - debug

- name: Stop docker, if started
  ansible.builtin.service:
    name: docker
    state: stopped
  ignore_errors: yes
  tags:
  - docker

#### Setup Docker
- name: Remove all docker-based existing packages
  apt:
    pkg:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - run
    state: absent
  tags:
  - docker
  - docker-remove # allow to skip removal of docker if known to be in good state
  - remove

- name: Install Docker 19+ packages
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - docker.io
    state: present
    update_cache: yes
  tags:
  - docker
  - docker-install # allows to skip docker install if known to be in good state

- name: Start docker, if not started
  ansible.builtin.service:
    name: docker
    state: started
  register: task_result
  until: task_result is succeeded
  retries: 10
  delay: 1
  tags:
  - docker

- name: Get Docker version
  command: docker version
  register: docker
  tags:
  - docker
  - debug

- name: Show output with docker version
  debug:
    msg: "{{ docker.stdout }}"
  tags:
  - docker
  - debug

- name: Add the docker group (NOTE, users will need to be manually added with `usermod` if needed)
  group:
    name: docker
    state: present
  tags:
  - docker
  - docker-user

# sudo usermod -aG docker root
- name: Add ansible_user user to "docker" group
  user:
    name: "{{ ansible_user }}"
    group: "docker"
    append: yes
  tags:
  - docker
  - docker-user

# - name: Re-establish shell with new group
#   command:
#     cmd: sudo su -l $USER
#   tags:
#   - docker
#   - docker-user

## UGH, hate that this has to happen (will check if using --become makes this no longer needed since root is in Docker group)
- name: Reboot machine to get new session with updated docker group
  reboot:
    reboot_timeout: 300
  tags:
  - docker
  - docker-user

- name: Verify docker can be run
  command:
    cmd: docker ps
  register: docker_output
  ignore_errors: yes
  tags:
  - docker
  - docker-user

- name: Output of Docker PS run
  debug:
    msg: "{{ docker_output.stdout }}"
  tags:
  - docker
  - debug
  - docker-user

- name: Set GCloud to authenticate docker
  command:
    cmd: gcloud auth configure-docker -q
  tags:
  - docker
  - docker-user