---
# tasks file for ready-ubuntu

### Verify OS is approved (Ubuntu only at this point). Saves the pre-checks later
- name: Fail if not running on Ubuntu 18.04 or 20.04
  fail:
    msg: "This playbook can only run on Ubuntu 18.04 or 20.04. Using {{ ansible_distribution }}:{{ ansible_distribution_version }}"
  when: ansible_distribution != "Ubuntu" or (ansible_distribution_version != '18.04' and ansible_distribution_version != '20.04')
  tags:
  - verify

- name: Install dependencies used in provisioning
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - wget
    - gnupg-agent
    - software-properties-common
    state: present
    update_cache: yes
  tags:
    - update-dependencies

#### Stop and disable apparmor
- name: Stop apparmor
  systemd:
    state: stopped
    name: apparmor
  tags:
  - remove

- name: Disable apparmor
  systemd:
    name: apparmor
    enabled: no
  tags:
  - remove

#### Disable ufw
- name: Disable wfw
  command: ufw disable
  register: ufw
  tags:
  - remove

- name: Show output for firewall stopping
  debug:
    msg: "{{ ufw.stdout }}"
  tags:
  - remove
  - debug

- name: "Setup docker on host machine"
  include: setup-docker-apt.yml
  tags:
  - docker
  # - never

## TODO: Take this out after the official fix has been committed
- name: Setup kernel in response to b/192342102
  command:
    cmd: sysctl net.netfilter.nf_conntrack_max=393216
  tags:
  - temp-fix
  - ubuntu-setup
