- name: Stop docker, if started
  ansible.builtin.service:
    name: docker
    state: stopped
  ignore_errors: yes

#### Setup Docker
- name: Remove all docker-based existing packages
  apt:
    pkg:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
    state: absent

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker 19+ packages
  apt:
    pkg:
    # Docker Community edition
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: true

- name: Start docker, if not started
  ansible.builtin.service:
    name: docker
    state: started
  register: task_result
  until: task_result is succeeded
  retries: 10
  delay: 5

- name: Get Docker version
  command: docker version
  register: docker

- name: Show output with docker version
  debug:
    msg: "{{ docker.stdout }}"

- name: Add the docker group (NOTE, users will need to be manually added with `usermod` if needed)
  group:
    name: docker
    state: present

# sudo usermod -aG docker root    [WARNING]: 'append' is set, but no 'groups' are specified. Use 'groups' for appending new groups.This will change to an error in Ansible 2.14.
- name: Add ansible_user user to "docker" group
  user:
    name: "{{ ansible_user }}"
    groups: "docker"
    append: yes

- name: Reset connection allowing docker group
  meta: reset_connection

- name: Verify docker can be run
  command:
    cmd: docker ps
  register: docker_output
  ignore_errors: yes

- name: Output of Docker PS run
  debug:
    msg: "{{ docker_output.stdout }}"

- name: Set GCloud to authenticate docker
  command:
    cmd: gcloud auth configure-docker -q
  environment:
    PATH: "{{ tools_base_path }}/google-cloud-sdk/bin:{{ ansible_env.PATH }}"
