#!/bin/bash
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ -f "/var/consumer-edge-install/scripts/shell-install-helper.sh" ]; then
    source "/var/consumer-edge-install/scripts/shell-install-helper.sh"
    display_help
else
    echo "Error: shell-install-helper.sh not found at /var/consumer-edge-install/scripts/shell-install-helper.sh"
    exit 1
fi
