# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


- name: Create temp folder
  ansible.builtin.tempfile:
    state: directory
    suffix: temp
    path: "/tmp"
  register: tmpfile
  tags:
  - pre-cache-unbundle

- name: Create a directory if it does not exist to keep ACM from failing
  ansible.builtin.file:
    path: "{{ acm_config_files | default('/var/acm-configs') }}"
    state: directory
    mode: '0755'

- name: Display path to Temp file
  debug:
    msg: "{{ tmpfile.path }}"
  tags:
  - pre-cache-unbundle

- name: Fetch bundle to temp folder
  include_tasks: unbundle-binaries.yml
  vars:
    fact_name: "unbundle_status"
    bundle_target: "{{ tmpfile }}"
  tags:
  - pre-cache-unbundle

- name: Fail if cannot fetch bundle and system MUST use cache
  ansible.builtin.fail:
    msg: "The Binaries Artifact tarball ({{ bundle_file_name }}) was not found and is required."
  when:
    - unbundle_status == false
    - must_use_precache | default(false) | bool

- name: Unpack bundle and explode to root filesystem
  ansible.builtin.unarchive:
    src: "{{ tmpfile.path }}/{{ bundle_file_name }}"
    dest: "/"
    remote_src: yes
  when: unbundle_status == true

- name: Cleanup temporary directory
  ansible.builtin.file:
    path: "{{ tmpfile.path }}"
    state: absent
  when: tmpfile.path is defined
