# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# {{local_cache_folder}}/config.csv
# bmctl,/usr/local/bin
# virtctl,/usr/bin/kubectl-virt
# kubens,/usr/local/bin/kubens
# kubectx,/usr/local/bin/kubectx
# k9s,/usr/local/bin/k9s
# config-management-operator.yaml,/var/acm-configs/config-management-operator.yaml

- name: Check if file exists at local folder
  stat:
    path: "{{ local_cache_folder }}/{{bundle_file_name}}"
  register: local_file_exists

- name: Copy local bundle to common location IF exists
  ansible.builtin.copy:
    src: "{{ local_cache_folder }}/{{bundle_file_name}}"
    dest: "{{ tmpfile.path }}/{{bundle_file_name}}"
    mode: '0644'
    remote_src: true
  when: local_file_exists.stat.exists

- name: Check if bucket exists when file does not
  ignore_errors: true
  command:
    cmd: "gsutil ls -al {{bucket_cache_url}}/{{bundle_file_name}}"
  register: bucket_file_exists
  when: not local_file_exists.stat.exists

- name: Copy bucket bundle to common location IF exists
  command:
    cmd: "gsutil cp {{bucket_cache_url}}/{{bundle_file_name}} {{ tmpfile.path }}/{{bundle_file_name}}"
  when:
  - not local_file_exists.stat.exists
  - bucket_file_exists.rc == 0

- name: Set flag to not-found
  set_fact:
    "{{ fact_name }}": False
  when:
  - not local_file_exists.stat.exists
  - bucket_file_exists.rc > 0

- name: Set fact that bundle was found
  set_fact:
    "{{ fact_name }}": True
