# SCM User
scm_user: "mock-gitlab-user"
# SCM Token
scm_token: "glpat-xxxxxxxxxxxxxxxxxxxx"

# OIDC ID { IF not set or empty, no OIDC is used }
oidc_id: "281813625367-ssssssssssssssssssssssss89.apps.googleusercontent.com"
# OIDC Secret { IF not set or empty, no OIDC is used }
oidc_secret: "-ud-mocked-O-a"

# SSH Public RSA Key
ssh_pub_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5xxxxxxxxxxxxxxxxxxxxgnfgf+Yerfejjrf872AHn7vaws example@localhost"
# SSH Private RSA Key
ssh_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  XXXXXXXXXXXXXXXXXXEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
  QyNTUxOQAAACCO2Bv7XXXXXXXXXXXXXXXXXXXXXXXX63/O9gB5+72sLAAAAJiC/mKxgv5i
  sQAAAAtzc2gtZWQyNTUxOQAAACCO2Bv721TGXXXXXXXXXXXXXXXXXXXX63/O9gB5+72sLA
  AAXXXXXXXXXXXXXXXXXXXXX9w+2H3/G3yO31+3F9J32t29/47YG/vbVMYT2fbcP6gnfgf+
  Yerfejjrf872AHn7vawsAAAAE2V4YW1wbGVAbG9jYWxob3N0AQ==
  -----END OPENSSH PRIVATE KEY-----

# Google Service Account JSON Key for Provisioning GSA
prov_gsa: |
  {
    "type": "service_account",
    "project_id": "gcp-project-id",
    "private_key_id": "mocked-key-id",
    "private_key": "-----BEGIN PRIVATE KEY-----\nMOCKED-PROV-GSA\n-----END PRIVATE KEY-----\n",
    "client_email": "target-machine-gsa@gcp-project-id.iam.gserviceaccount.com"
  }

# Google Service Account JSON Key for Node GSA
node_gsa: |
  {
    "type": "service_account",
    "project_id": "gcp-project-id",
    "private_key_id": "mocked-node-key-id",
    "private_key": "-----BEGIN PRIVATE KEY-----\nMOCKED-NODE-GSA\n-----END PRIVATE KEY-----\n",
    "client_email": "provision-gsa@gcp-project-id.iam.gserviceaccount.com"
  }
