# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
## Update file descriptor limits
- name: "Copy script to optimize FD limits"
  template:
    src: optimize-fd-limits.sh.j2
    dest: "{{ abm_install_folder }}/optimize-fd-limits.sh"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "0744"
  tags:
  - update-dependencies
  - ubuntu-setup
  - fd-limits
  - update-fswatch

- name: "Run script to optimize FD limits"
  command: "{{ abm_install_folder }}/optimize-fd-limits.sh"
  register: fd_optimization
  tags:
  - update-dependencies
  - ubuntu-setup
  - fd-limits
  - update-fswatch
