###
### Setup Time Sync using Datetime Config
###

- name: Remove NTP Package
  apt:
    pkg:
    - ntp
    state: absent
  tags:
  - time-sync-setup
  when:
  - target_os == "ubuntu"

- name: Disable systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    enabled: no
    state: stopped
  tags:
  - time-sync-setup
  when:
  - target_os == "ubuntu"

- name: Install chrony
  apt:
    name: chrony
    state: present
    update_cache: yes
  tags:
  - time-sync-setup
  when:
  - target_os == "ubuntu"

- name: Setup TimeZone Data
  community.general.timezone:
    name: "{{ machine_timezone }}"
  tags:
  - time-sync-setup

- name: Template chrony.conf
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload chrony
  tags:
  - time-sync-setup

- name: Ensure chrony is started and enabled
  systemd:
    name: chrony
    state: started
    enabled: yes
  tags:
  - time-sync-setup
