---

# Variables assigned to all inventory

google_project_id: "{{ lookup('env', 'PROJECT_ID') }}"
google_region: "{{ lookup('env', 'REGION') | default('us-central1', True) }}"
google_zone: "{{ lookup('env', 'ZONE') | default('us-central1-a', True) }}"
local_gsa_key: "{{ lookup('env', 'LOCAL_GSA_FILE') }}"
tools_base_path: "/var/google-tools-install"

kubeconfig_shared_root: "/var/kubeconfig"
kubeconfig_shared_location: "{{ kubeconfig_shared_root }}/kubeconfig"

# SCM (GitLab, GitHub access token)
scm_token_user: "{{ lookup('env', 'SCM_TOKEN_USER') }}"
scm_token_token: "{{ lookup('env', 'SCM_TOKEN_TOKEN') }}"

gcs_bucket_guest_vm: "anthos-consumer-edge-vm-isos"
vm_guest_image: "windows-server-2016-eval-en-us.iso"

# ACM (using 'token' method)
acm_root_repo: "https://gitlab.com/gcp-solutions/app-mod/sm002-consumer-edge/consumer-retail-edge/root-repo-usa-market.git"

# git_creds_gcp_secret_name is the secret created to hold the Git PAT info corresponding to that Namespace Repo
# franchise_name, franchise_number aren't used
# Stores: not used now, secrets are created for all franchises in GCP Secrets Manager, ExternalSecrets are controlled in the root-repo for each franchise
#      Associations of franchise/store -> cluster is done at the inventory level on "acm_cluster_name" (an unique name across the cluster space)
franchises: [
  {
    franchise_number: "123",
    git_creds_gcp_secret_name: "franchise-123-git-creds", # Secret to access the namespace repo containing the franchise's information
    franchise_name: "ACME",
    stores: [
      "cnuc-1" # store-usa-123-1
    ]
  },
  {
    franchise_name: "Innotec",
    franchise_number: "234",
    git_creds_gcp_secret_name: "franchise-234-git-creds",
    stores: [
      "nuc-1" # store-usa-234-3
    ]
  },
  {
    franchise_name: "Penatrode",
    franchise_number: "123",
    git_creds_gcp_secret_name: "franchise-123-git-creds",
    stores: [
      "cnuc-4" # store-usa-123-2
    ]
  },
  {
    franchise_name: "UberTrinken",
    franchise_number: "234",
    git_creds_gcp_secret_name: "franchise-234-git-creds",
    stores: [
      "nuc-4" # store-usa-234-2
    ]
  }
]
